image:
  file: Dockerfile
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
# enable for all branches in this repo (defaults to false)
    branches: true
# enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
# enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
# add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
# add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: true
# add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
tasks:
- command: python3 main.py
- command: bash setup_pycalc.sh
vscode:
  extensions:
    - almenon.arepl@1.0.16:XGYMBgfBMAnJXoyFkfSzPA==
    - KevinRose.vsc-python-indent@1.4.0:pb+bIlsFJOAdUNBE31dQwQ==
    - ms-python.python@2019.6.24221:eSSDlQYifwrEZXcrjL0W/g==
    - ms-python.anaconda-extension-pack@1.0.1:zDfOOe7FoQk40SnrhxWS5g==
    - eamodio.gitlens@9.9.2:4mgTdhdGJaQTZHTMTMDPYg==
    - ms-vsliveshare.vsliveshare-pack@0.3.2:0K1J2luvqWif20PhMHupAA==
    - mgesbert.python-path@0.0.11:JKeT9N0dYesuMTRK8HkQsw==
    - littlefoxteam.vscode-python-test-adapter@0.3.8:/OHYOvT+03UvxFOXfFt2Ew==
    - vscjava.vscode-java-pack@0.7.1:ea31zLwuaUsRabxq6oqI1w==
    - DavidAnson.vscode-markdownlint@0.29.0:BLKb9Vn6CqVXSiurVk5sTg==
    - vscode-icons-team.vscode-icons@9.2.0:Ijpf7hzDdyz46hvWWPc41Q==
    - vscjava.vscode-java-debug@0.20.0:2XzlrnOFsFzAHrOc51/R6w==
    - streetsidesoftware.code-spell-checker@1.7.17:k6J87NQRojNS1DjwmZSSLg==
    - redhat.java@0.47.0:1+7JOWQwVz4ve3Yx6/vWdw==
    - donjayamanne.python-extension-pack@1.6.0:d2CAGx1tkZr49Mg/VZx4Hw==
    - tht13.python@0.2.3:1RPVn9AW+lkCOD6zUWqiIw==
    - VisualStudioExptTeam.vscodeintellicode@1.1.9:osawgVS7+7lo2813SXOJng==
    - donjayamanne.git-extension-pack@0.1.3:SfFwfST7Hdp+r/KRulDGXA==
    - davidrockburn.py-pack@1.2.0:mSeo52qtBjzmDMrutXyFlg==
    - igress.python-coding-conventions@0.0.4:smziTduPUGSQJLXnsi44qg==
    - jeff-hykin.better-dockerfile-syntax@1.0.0:iyUO24NLuOKURAhRxmXz3A==
    - ms-azuretools.vscode-docker@0.7.0:lYnHNvokI7NuPc2r/XuWRw==
    - zalo.symplex@0.0.8:ZftGU13OMy/bJDv4reqVWg==
    - beeware.beeware@0.0.1:7Tn3+C59NuY5CpnzOh22PA==
    - yixian.yapep@0.0.3:lvaXr74ecbxL0wWVvKSIwQ==
    - LeoJhonSong.python-extension-pack@0.1.1:s3sTtYbjRdCJgSd3Se7c2A==
    - dongli.python-preview@0.0.4:nvty7iTDVzgjTWYf1k+/iw==
    - tushortz.python-extended-snippets@0.0.1:29rXD9fAGGowAVB+BUS1Ww==
    - nils-ballmann.python-coding-tools@1.0.3:u+UDC4J3U1ZQqa80dt/Bew==
    - Compulim.compulim-vscode-closetag@1.2.0:GWnzouwI3h+e3s+0i9HU2Q==
    - hbenl.vscode-test-explorer@2.14.1:IRVt8LieiXZoxG/oYJtuVQ==
    - njpwerner.autodocstring@0.3.0:o5YAMxwX1VEiRJrh/BbPYg==
    - abusaidm.html-snippets@0.2.1:7b7Vkkp6Lem9WOqKCYMq2w==
    - mohd-akram.vscode-html-format@0.0.3:8VbAWgIB5qCah4IYSl+KxQ==
    - formulahendry.auto-close-tag@0.5.6:oZ/8R2VhZEhkHsoeO57hSw==
    - iansan5653.format-python-docstrings@1.0.2:7iicn7EF2Pyz2JVPc5VQMA==
    - batisteo.vscode-django@0.19.0:GOHmg6fGCbzkKe2S73i7Ig==
    - vscjava.vscode-maven@0.18.1:Ga0twwGQDu7XhFR1f838vg==
    - yzhang.markdown-all-in-one@2.4.2:BCNsQbcvf8Dm1nmMSvypJA==
ports:
  - port: 3000
    onOpen: open-preview
  - port: 5000
    onOpen: open-preview
